version: '3'
services:
  nginx:
    build: nginx
    container_name: teamfinder-nginx
    ports:
      - 80:8080
    volumes:
      - ./public:/var/www/public
      - ./backend:/var/www/backend
      - ./logs/nginx:/var/log/nginx
      - composer-vendor:/var/www/vendor
    links:
      - php
  php:
    build: php
    container_name: teamfinder-php
    volumes:
      - ./public:/var/www/public
      - ./backend:/var/www/backend
      - ./logs/php:/var/log/php
      - composer-vendor:/var/www/vendor
    links:
      - composer
      - mysql
  composer:
    container_name: teamfinder-composer
    build:
      context: .
      dockerfile: Dockerfile.Composer
    volumes:
      - composer-vendor:/var/www/vendor
  mysql:
    build: mysql
    container_name: teamfinder-mysql
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
  php-unit:
    container_name: teamfinder-php-unit
    build:
      context: .
      dockerfile: Dockerfile.PHPUnit
    links:
      - composer
    volumes:
      - composer-vendor:/var/www/vendor

volumes:
  composer-vendor: