version: '3'
services:
    nginx:
        build: nginx
        ports:
            - 80:8080
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - .:/var/www
            - ./logs/nginx:/var/log/nginx
        links:
            - php
    php:
        build: php
        volumes:
            - .:/var/www
            - ./logs/php:/var/log/php
        links:
            - mysql
    mysql:
        build: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret

