version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-cli
    steps:
      - checkout
      - run:
        name: Install Docker Compose
        command: |
          curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
        name: Install Composer
        command: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - run:
        name: Building...
        command: |
          composer install
          docker-compose up -d
        when: always
  php-tests:
    steps:
      - checkout
      - run:
        name: PHP Tests
        command: |
          mkdir -p ~/phpunit
          vendor/bin/phpunit --log-junit ~/phpunit/junit.xml ./tests/backend
        when: always
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build