version: 2.1
aliases:
  - &working_directory ~/team-finder  

executors:
  php7:
    docker:
      - image: circleci/php:7.2-cli
    working_directory: *working_directory

jobs:
  build:
    executor: php7
    steps:
      - checkout
      - run: ls
      - run: curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
      - run: chmod +x ~/docker-compose
      - run: sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"      
      - run: composer install
      - save_cache:
          key: build-cache-{{ .Revision }}
          paths:
            - *working_directory
  php-tests:
    executor: php7
    steps:
      - restore_cache:
          keys:
            - build-cache-{{ .Revision }}
      - run: mkdir -p artifacts/phpunit/PHPUnit
      - run: vendor/bin/phpunit --log-junit artifacts/phpunit/PHPUnit/junit.xml ./tests/backend
      - store_test_results:
          path: artifacts/phpunit/PHPUnit
      - store_artifacts:
          path: artifacts/phpunit/PHPUnit
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - php-tests:
          requires:
            - build